package Fila;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * @author Gabriel Yudi Sanefugi - RA:160027
 */

public class FilaJFM extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form FilaJFM
     */
    private Fila f = new Fila(10, 25, 150); //configura em desenho seu tamanho
    private boolean inserir = false;
    private boolean remover = false;
    
    public FilaJFM() {
        initComponents();
        myInitComponents();
        createBufferStrategy(2);
        Thread t = new Thread (this); 
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     private void myInitComponents() 
     {
         addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilaJFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilaJFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilaJFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilaJFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilaJFM().setVisible(true);
            }
        });
    }

    @Override
    public void run() 
    {
        Graphics g;
        
        while(true)
        {
            g = getBufferStrategy().getDrawGraphics();
            
            //Prepara o basico
            g.setColor(Color.WHITE);
            g.fillRect(0, 0, getWidth(), getHeight());
            
            if(inserir)
            {
                try
                {
                    f.inserir(new Retangulo());

                    System.out.println("Inseriu, tamanho atual: "+f.quantidade());
                }
                catch(Exception e)
                {
                    //Notificar usuario que ficou cheio

                    System.out.println(e);
                }
                
                inserir = false;
            }
           
            if(remover)
            {
                try
                {
                    f.remove();
                    System.out.println("Removeu, tamanho atual: "+f.quantidade());
                }
                catch(Exception e)
                {
                    //Notificar usuario que esta vazio
                    System.out.println(e);
                }
                remover = false;
            }
            //Desenha a fila
            f.desenha(g);
            
            g.dispose();
            getBufferStrategy().show();
            
            /*try 
            {
                Thread.sleep(30);
            } 
            catch (InterruptedException ex) 
            {
                Logger.getLogger(FilaJFM.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        }
    }
    
    private void formKeyPressed(java.awt.event.KeyEvent evt)
    {                                
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) 
        {
            inserir = true;
        } 
        else if (evt.getKeyCode() == KeyEvent.VK_LEFT) 
        {
            remover = true;
                        
        }
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
